# Generated by Django 4.2.1 on 2023-05-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_content_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
