# Generated by Django 4.2.1 on 2023-06-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_content_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.IntegerField(choices=[(0, 'پیش نویس'), (1, 'منتشر شده')], default=0),
        ),
    ]
