# Generated by Django 4.2.1 on 2023-06-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_content_author_alter_content_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='تگ ها'),
        ),
    ]
