# Generated by Django 4.2.1 on 2023-06-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='email',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='images/template/'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='footer_logo',
            field=models.ImageField(blank=True, upload_to='images/template/'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/template/'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='logo_small',
            field=models.ImageField(blank=True, upload_to='images/template/'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='work_time',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
