# Generated by Django 4.2.1 on 2023-06-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_websitesetting_about_websitesetting_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='images/template/fav.png'),
        ),
    ]
