# Generated by Django 4.2.1 on 2023-06-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_websitesetting_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='images/template/'),
        ),
    ]
