# Generated by Django 4.2.1 on 2023-06-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_websitesetting_favicon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitesetting',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='about',
            field=models.TextField(blank=True, default='', verbose_name='درباره ما'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='email',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='images/template/', verbose_name='ایکن'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='footer_logo',
            field=models.ImageField(blank=True, upload_to='images/template/', verbose_name='لوگو فوتر'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/template/', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='logo_small',
            field=models.ImageField(blank=True, upload_to='images/template/', verbose_name='لوگو کوچک'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='work_time',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='ساعت کاری'),
        ),
    ]
