# Generated by Django 4.2.1 on 2023-06-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_headermenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='headermenu',
            name='link',
            field=models.SlugField(default='', verbose_name='پیوند'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headermenu',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='نام'),
            preserve_default=False,
        ),
    ]
