# Generated by Django 4.2.1 on 2023-06-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_navmenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderMenu',
        ),
    ]
