# Generated by Django 4.2.1 on 2023-06-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_headermenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navmenu',
            name='link',
            field=models.SlugField(blank=True, default='', verbose_name='لینک'),
        ),
    ]
