# Generated by Django 4.2.1 on 2023-06-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_navmenu_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navmenu',
            name='link',
            field=models.URLField(default='', verbose_name='لینک'),
        ),
    ]
