# Generated by Django 4.2.1 on 2023-06-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_navmenu_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='desc',
            field=models.TextField(default='', verbose_name='توضیحات اضافه'),
        ),
    ]
