# Generated by Django 4.2.1 on 2023-06-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_slider_image_slider_link_slider_short_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='address',
            field=models.CharField(blank=True, default='', max_length=70, verbose_name='آدرس'),
        ),
    ]
